# Generated by Django 6.0.6 on 2026-06-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
